server:
    port: 8097
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:9091/eureka/
        lease:
            duration: 5
spring:
    application:
        name: web-socket-service