server:
  ports:
    http: 8075
  port: 8094

  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  data:
    mongodb:
      database: SearchDB
      host: localhost
      port: 27017
  application:
    name: upstream-service